package com.aegis.common.model;

public enum PipelineStep {
    // V48 production path: no Bandai, no BVH, no FBX, no Unreal IK Retargeter.
    V48_LOAD_GOLD_OVERLAY,
    V48_GENERATE_SYNTHETIC_VARIANTS,
    V48_BUILD_QUATERNION_DATASET,
    V48_TRAIN_QUATERNION_PRIOR,
    V48_GENERATE_IMPORT_JSON,
    V48_VALIDATE_IMPORT_JSON,

    // Legacy / experimental Bandai path retained for research only.
    CLONE_BANDAI_REPO,
    EXTRACT_BANDAI_DATA,
    SELECT_BANDAI_CLIPS,
    OFFLINE_RETARGET_TO_MANNY_JSON,
    CONVERT_BVH_TO_FBX,
    IMPORT_FBX_TO_UNREAL,
    WAIT_FOR_MANUAL_RETARGET,
    EXPORT_RETARGETED_ANIMSEQUENCES,
    BUILD_TRAINING_MANIFEST,
    BUILD_TENSOR_DATASET,
    TRAIN_NEURAL_MOTION_PRIOR,
    GENERATE_OVERLAY_JSON,
    VERIFY_OVERLAY_JSON,
    COMPLETE
}
